### ISSUE TITLE
Should there be .dvc files, or a .sh script for setup?

### ISSUE THREAD

**Issue by robogeek** [iterative/dvc-doc-get-started#1]
I see this repository has .dvc files already in place.  It might be more instructive to the user to instead have a shell script that runs the setup, and the .dvc files are generated as a side-effect of that script.

**Comment by shcheklein** [comment]
To answer the question. In that auto-generated repo (`create.sh` script from this repo generates it) there should be the final result and probably some tags like `step1`, `step2`, etc, so that we can just checkout a specific step and go from there.
